version: '3.8'

services:
  ui_service:
    build: ./ui_service
    ports:
      - "5000:5000"
    volumes:
      - ./ui_service:/app
    environment:
      - FLASK_SECRET_KEY=supersecretkey

  whisper_service:
    build: ./whisper_service
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  topic_service:
    build: ./topic_service
    ports:
      - "8001:8001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
